// Copyright 2020 Tobias
#ifndef SRC_LIB_ABSTRACT_DATES_MES_HPP_
#define SRC_LIB_ABSTRACT_DATES_MES_HPP_

enum Mes {
  JANEIRO = 1, FEVEREIRO, MARCO, ABRIL, MAIO, JUNHO, JULHO, AGOSTO, SETEMBRO,
  OUTUBRO, NOVEMBRO, DEZEMBRO
};

#endif  // SRC_LIB_ABSTRACT_DATES_MES_HPP_
