#ifndef SRC_LIB_FILE_FILE_PLUGINS_ATTACHMENT_ATTACHMENT_HPP
#define SRC_LIB_FILE_FILE_PLUGINS_ATTACHMENT_ATTACHMENT_HPP

class Anexo {};

#endif  // SRC_LIB_FILE_FILE_PLUGINS_ATTACHMENT_ATTACHMENT_HPP
