// Copyright 2020 Tobias
#ifndef SOLUCAO_LIB_ABSTRACT_DATES_MES_HPP_
#define SOLUCAO_LIB_ABSTRACT_DATES_MES_HPP_

enum Mes {
  JANEIRO = 1, FEVEREIRO, MARCO, ABRIL, MAIO, JUNHO, JULHO, AGOSTO, SETEMBRO,
  OUTUBRO, NOVEMBRO, DEZEMBRO
};

#endif  // SOLUCAO_LIB_ABSTRACT_DATES_MES_HPP_
